package net.minecraft.railsys.render;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.railsys.modelpack.RailsysAssetBundle;
import net.minecraft.railsys.modelpack.RailsysAssetRegistry;
import net.minecraft.railsys.modelpack.RailsysInternalAsset;
import net.minecraft.railsys.modelpack.RailsysInternalAsset.Compatibility;

/**
 * RailsysModelPackClient — game-layer bridge for Railsys-native ModelPack
 * assets (Phase 1-R15).
 *
 * The TeaVM web runtime cannot read ModelPack ZIP files from disk, so the
 * import path is the Railsys-native asset bundle JSON produced by the JVM-side
 * compatibility adapter (see RailsysAssetBundle / ModelPackImporter). This
 * class:
 *   - registers bundle assets into the geometry-core RailsysAssetRegistry
 *   - holds the CURRENT rail asset selection (packId:railId)
 *   - lists assets / packs / compatibility for the Shift+RightClick selector
 *   - maps a RailsysInternalAsset to the R14 production appearance profile
 *     (gauge, ballast, component-derived look) WITHOUT touching RailPath
 *
 * The bundle carries ONLY spec facts (names, components, ballast, renderer
 * behaviour, texture refs) — never RTM models/textures/scripts.
 */
public final class RailsysModelPackClient {

	private static volatile String currentAssetId = RailsysAssetRegistry.FALLBACK_ASSET_ID;
	private static boolean fallbackEnsured = false;
	private static boolean bundleLoaded = false;

	private RailsysModelPackClient() {
	}

	public static synchronized void ensureInitialized() {
		if (!fallbackEnsured) {
			fallbackEnsured = true;
			RailsysAssetRegistry.ensureFallback();
		}
		ensureEmbeddedBundleLoaded();
	}

	/**
	 * Load the embedded Railsys-native bundle (generated by the JVM adapter
	 * from the real reference ModelPack) exactly once. Idempotent.
	 */
	public static synchronized void ensureEmbeddedBundleLoaded() {
		if (bundleLoaded) {
			return;
		}
		bundleLoaded = true;
		importBundle(RailsysModelPackBundle.bundleJson());
	}

	/**
	 * Import a Railsys-native bundle JSON (dev/command path). Returns the
	 * number of assets registered; invalid bundles return 0 (never throws).
	 * Duplicate asset ids WITHIN one bundle are rejected (a second registration
	 * of the same id is refused — see RailsysAssetRegistry.register). Reload of
	 * an existing pack is handled by first removing the old pack's assets.
	 */
	public static synchronized int importBundle(String bundleJson) {
		ensureInitialized();
		List<RailsysInternalAsset> assets = RailsysAssetBundle.parseBundle(bundleJson);
		int registered = 0;
		java.util.Set<String> seen = new java.util.HashSet<String>();
		for (RailsysInternalAsset a : assets) {
			if (!seen.add(a.assetId)) {
				System.out.println("railsys: modelpack duplicate assetId rejected: " + a.assetId);
				continue;
			}
			// Reload semantics: if the id already exists (same pack re-import),
			// replace it; a fresh id is registered. Duplicates WITHIN this
			// bundle are already rejected above.
			RailsysAssetRegistry.remove(a.assetId);
			if (RailsysAssetRegistry.register(a)) {
				registered++;
			}
		}
		System.out.println("railsys: modelpack bundle import registered=" + registered + "/" + assets.size());
		return registered;
	}

	/** Reset to the built-in fallback asset. */
	public static synchronized void resetToFallback() {
		ensureInitialized();
		currentAssetId = RailsysAssetRegistry.FALLBACK_ASSET_ID;
	}

	public static String currentAssetId() {
		ensureInitialized();
		return currentAssetId;
	}

	/** Set the current asset id (falls back if unknown/duplicate-safe). */
	public static synchronized boolean setCurrentAsset(String assetId) {
		ensureInitialized();
		RailsysInternalAsset a = RailsysAssetRegistry.get(assetId);
		if (a != null && !a.assetId.equals(RailsysAssetRegistry.FALLBACK_ASSET_ID)) {
			currentAssetId = a.assetId;
			System.out.println("railsys: modelpack current asset -> " + currentAssetId
					+ " compat=" + a.compatibility + " components=" + a.components);
			return true;
		}
		// Unknown -> keep fallback
		System.out.println("railsys: modelpack asset unknown, keeping " + currentAssetId);
		return false;
	}

	/** The current asset (never null; falls back when unregistered). */
	public static RailsysInternalAsset currentAsset() {
		ensureInitialized();
		return RailsysAssetRegistry.get(currentAssetId);
	}

	/** Asset by id (falls back when missing). */
	public static RailsysInternalAsset asset(String id) {
		ensureInitialized();
		return RailsysAssetRegistry.get(id);
	}

	public static List<String> assetIds() {
		ensureInitialized();
		return RailsysAssetRegistry.ids();
	}

	public static List<String> packIds() {
		ensureInitialized();
		return RailsysAssetRegistry.packIds();
	}

	public static List<String> assetIdsForPack(String packId) {
		ensureInitialized();
		return RailsysAssetRegistry.idsForPack(packId);
	}

	public static int assetCount() {
		ensureInitialized();
		return RailsysAssetRegistry.size();
	}

	/** Selected asset is ModelPack-derived (not the built-in fallback). */
	public static boolean hasModelPackAsset() {
		ensureInitialized();
		RailsysInternalAsset a = RailsysAssetRegistry.get(currentAssetId);
		return a != null && !a.assetId.equals(RailsysAssetRegistry.FALLBACK_ASSET_ID);
	}

	/**
	 * Map a RailsysInternalAsset to an R14 appearance profile. Geometry NEVER
	 * changes: the RAIL OFFSETS (left/right) come from the segment's
	 * AUTHORITATIVE gauge snapshot (segmentGaugeM), NOT the asset's gauge
	 * metadata. Asset gauge (when present) is metadata only. Only colours,
	 * ballast/sleeper flags and material are derived from the asset facts.
	 */
	public static net.minecraft.railsys.render.RailProfile profileForAsset(RailsysInternalAsset a,
			double segmentGaugeM) {
		if (a == null) {
			return net.minecraft.railsys.render.RailProfile.default1435();
		}
		net.minecraft.railsys.render.RailProfile base = net.minecraft.railsys.render.RailProfile.default1435();
		double gauge = segmentGaugeM;
		// Asset gaugeM is NEVER applied to geometry — the segment snapshot wins.
		// (R15 F4: gauge invariance — asset = look only.)
		// Ballast: pack defaultBallast blockName -> base slab.
		boolean hasBallast = a.ballastBlock != null && !a.ballastBlock.isEmpty()
				&& !a.ballastBlock.equalsIgnoreCase("air");
		double ballastWidth = hasBallast ? 2.6D : 0.0D;
		double ballastDepth = hasBallast ? 0.22D : 0.0D;
		int baseR = hasBallast ? 90 : 0;
		int baseG = hasBallast ? 78 : 0;
		int baseB = hasBallast ? 62 : 0;

		// Rail colour: derive a stable Railsys-native look from the asset's
		// railId (original mapping, NOT copied from the pack texture).
		int[] railCol = railColourFor(a.railId);

		return new net.minecraft.railsys.render.RailProfile(
				base.headWidthM, base.headHeightM, base.webWidthM, base.webHeightM,
				base.footWidthM, base.footHeightM, gauge,
				railCol[0], railCol[1], railCol[2],
				base.hasSleeper, base.sleeperSpacingM, base.sleeperLengthM, base.sleeperWidthM,
				base.sleeperHeightM, base.sleeperTopM, base.sleeperR, base.sleeperG, base.sleeperB,
				base.hasFastener, base.fastenerSpacingM,
				hasBallast, ballastWidth, ballastDepth, baseR, baseG, baseB,
				a.materialId);
	}

	/** Stable Railsys-native rail colour derived from the rail id (original). */
	private static int[] railColourFor(String railId) {
		String id = railId == null ? "" : railId.toLowerCase();
		if (id.contains("steel")) return new int[] { 120, 122, 128 };
		if (id.contains("wood")) return new int[] { 96, 78, 56 };
		if (id.contains("grass") || id.contains("gras")) return new int[] { 84, 96, 62 };
		if (id.contains("asphalt") || id.contains("pflaster")) return new int[] { 92, 92, 96 };
		if (id.contains("dss")) return new int[] { 138, 140, 146 };
		if (id.contains("concrete") || id.contains("ffb") || id.contains("nbs")) return new int[] { 150, 152, 158 };
		return new int[] { 110, 110, 120 };
	}
}
